"""initial_schema

Revision ID: 8f1fcd986a0f
Revises: 
Create Date: 2026-05-10 23:25:47.754566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1fcd986a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_normalized', sa.String(length=500), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('current_currency', sa.String(length=10), nullable=False),
    sa.Column('current_original_price', sa.Float(), nullable=True),
    sa.Column('current_discount_pct', sa.Float(), nullable=True),
    sa.Column('is_on_sale', sa.Boolean(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('alert_threshold_pct', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url', name='uq_product_url')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_product_name_normalized', ['name_normalized'], unique=False)
        batch_op.create_index('ix_product_store', ['store'], unique=False)

    op.create_table('monitored_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scrape_interval_hours', sa.Integer(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_scrape_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url', name='uq_monitored_url')
    )
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_price_alerts_notified', ['is_notified'], unique=False)
        batch_op.create_index('ix_price_alerts_product_created', ['product_id', 'created_at'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('is_on_sale', sa.Boolean(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('spider_name', sa.String(length=100), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_product_scraped', ['product_id', 'scraped_at'], unique=False)
        batch_op.create_index('ix_price_history_scraped_at', ['scraped_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_scraped_at')
        batch_op.drop_index('ix_price_history_product_scraped')

    op.drop_table('price_history')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_price_alerts_product_created')
        batch_op.drop_index('ix_price_alerts_notified')

    op.drop_table('price_alerts')
    op.drop_table('monitored_urls')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_product_store')
        batch_op.drop_index('ix_product_name_normalized')

    op.drop_table('products')
    # ### end Alembic commands ###
